version: '3.2'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:14'
    environment:
      - POSTGRES_DB=web_scrapers
      - POSTGRES_PASSWORD=Password@1234
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/

  redis:
    container_name: 'redis'
    image: 'redis:4.0.6-alpine'
    command: 'redis-server --requirepass "$REDIS_PASSWORD"'
    environment:
      - REDIS_PASSWORD=Password@1234
    ports:
      - '6379:6379'

volumes:
  pg_data:
